import { Inter,Rubik_Doodle_Shadow,Teko ,Caveat} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const rubik = Caveat({
  subsets: ["latin"],
  variable: "--rubik",
  weight: ["400"],
});


export const metadata = {
  title: "hashGPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <main className={(rubik.variable)}>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
